### ISSUE TITLE
Kinect Sensor recognition

### ISSUE THREAD

**Issue by hoangduyloc** [YugAjmera/navros_pkg#1]
Hello Yug, Thanks for your great job. I have a question is  How can you run "rosrun teleop_twist_keyboard teleop_twist_keyboard.py" without Gazebo simulation?I want to run the real robot and Kinect camera sensor, seems I can not run

**Comment by YugAjmera** [comment]
Hi @hoangduyloc. The teleop_twist_keyboard.py file sends velocity commands on the `/cmd_vel` topic by default. I would suggest you check the velocity command topic on your real robot. Then you can run:
`rosrun teleop_twist_keyboard teleop_twist_keyboard.py cmd_vel:=your_topic_name`

**Comment by hoangduyloc** [comment]
@YugAjmera
I will check based on your advice. Thank you so much!

**Comment by hoangduyloc** [comment]
@YugAjmera 
One more question is I just want to build the octomap from Kinect sensor only, and don't need the robot using your code. But after runing the  "gmapping.launch" and "octomap.launch"  file I see the result below, I don't have the resolution of octomap. I'm really new to ROS, so my question is may not good question. Thank you
![image](https://user-images.githubusercontent.com/38793688/96003173-e66f9680-0e74-11eb-9e1a-2189f22997b9.png)

**Comment by YugAjmera** [comment]
@hoangduyloc It's very hard to say anything from the screenshot you have shared. You need the robot for creating the octomap because without it it will plot everything on the same place.

**Comment by hoangduyloc** [comment]
@YugAjmera 
I will try to figure out the problem and read more about these things. Thanks for your help!

**Comment by YugAjmera** [comment]
I am closing this issue then.
